
sudo: required
service:
  - docker

before_install:
  - docker build -t gannpm/docker-react -f Dockerfile.dev .

script:
  - docker run gannpm/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-270403973640"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  


#  Docker-env.x2qmrpiey9.us-west-2.elasticbeanstalk.com
#S3 container
# elasticbeanstalk-us-west-2-270403973640

#IAM - AWS Id and Pwd stored in .travis-ci.org
# $AWS_ACCESS_KEY
# $AWS_SECRET_KEY

# https://s3.console.aws.amazon.com/s3/buckets/elasticbeanstalk-us-west-2-270403973640/?region=us-west-2&tab=overview
