
sudo: reuired
service:
  - docker

before_install:
  - docker build -t gannpm/docker-react -f Dockerfile_dev .

script:
  - docker run gannpm/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  # provider: s3
  region: "us-west-2"
  app: "docker"
  env: "docker-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-270403973640"
  # bucket_path: "docker"
  bucket_path: http://s3-aws-region.amazonaws.com/bucket
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: 
    secure: $AWS_SECRET_ACCESS_KEY
  




