
{
  "services": [
    "docker"
  ], 
  "sudo": "required", 
  "before_install": [
    "docker build -t gannpm/docker-react -f Dockerfile.dev ."
  ], 
  "deploy": {
    "true": {
      "branch": "master"
    }, 
    "region": "us-west-2", 
    "bucket_path": "docker", 
    "secret_access_key": "$AWS_SECRET_KEY", 
    "access_key_id": "$AWS_ACCESS_KEY", 
    "bucket_name": "elasticbeanstalk-us-west-2-270403973640", 
    "env": "Docker-env", 
    "provider": "elasticbeanstalk", 
    "app": "docker"
  }, 
  "script": [
    "docker run gannpm/docker-react npm run test -- --coverage"
  ]
}



Docker-env.w2zt86gv5t.us-west-2.elasticbeanstalk.com
