
sudo: required
services:
  - docker

before_install:
  - docker build -t gannpm/docker-react -f Dockerfile.dev .

script:
  - docker run gannpm/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-270403973640"
  bucket_path: "docker"
  
  on:
    branch: master
  ACCESS_KEY_ID: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
